name = "vega-editor-backend"
main = "./dist/app.js"
compatibility_date = "2024-12-01"

[env.production.vars]
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
SESSION_SECRET = ""

[build]
command = "npm run build"

[[routes]]
pattern = "*"
custom_domain = true

[observability.logs]
enabled = true
