name = "editor-backend"
main = "./dist/app.js"
compatibility_date = "2025-06-01"

[build]
command = "npm run build"

[[routes]]
pattern = "*"
custom_domain = true

[observability.logs]
enabled = true
